register:
  path: /api/register
  controller: App\Controller\LoginController::register
  methods: [POST]

api:
  path: /api
  controller: App\Controller\LoginController::api

login_check:
  path:     /api/authenticate
  methods:  [POST]

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

