export enum Fonction {
  MINISTRE = 'MINISTRE',

  SG = 'SG',

  CHARGE_MISSION = 'CHARGE_MISSION',

  CONSEILLER = 'CONSEILLER',

  INSPECTEUR = 'INSPECTEUR',

  DIRECTEUR = 'DIRECTEUR',

  DIRECTEUR_ADJOINT = 'DIRECTEUR_ADJOINT',

  CHEF_SERVICE = 'CHEF_SERVICE',

  ATTACHE = 'ATTACHE',

  CHEF_DIVISION = 'CHEF_DIVISION',

  CADRE = 'CADRE',

  AUTRE = 'AUTRE',
}
